<?php
namespace App\Controller;

use App\Controller\AppController;

/**
 * Contractorqr Controller
 *
 * @property \App\Model\Table\ContractorqrTable $Contractorqr
 */
class ContractorqrController extends AppController
{

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->Auth->allow();
        $this->layout='portal';
    }

    /**
     * Index method
     *
     * @return void
     */
    public function index($id)
    {
        $this->layout = 'ajax';
        $this->loadModel('ContractorDocuments');
        $file = $this->ContractorDocuments->find('all')->where(['contractor_id' => $id])->first();
        $this->set(compact('file'));
    }

}
