<?php
namespace App\Controller;

use App\Controller\AppController;
use Cake\ORM\TableRegistry;

/**
 * Evidence Controller
 *
 * @property \App\Model\Table\EvidenceTable $Evidence
 */
class EvidenceController extends AppController
{

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->Auth->allow();
        $this->layout='portal';
    }

    /**
     * Index method
     *
     * @return void
     */
    public function index($id)
    {
        $this->layout = 'ajax';
        $this->loadModel('Documents');
        $file = $this->Documents->find('all')->where(['scheme_id' => $id])->first();
        $this->set(compact('file'));
    }

}
