<?php
namespace App\Controller;

use App\Controller\AppController;
use Cake\ORM\TableRegistry;

/**
 * Evidence Controller
 *
 * @property \App\Model\Table\EvidenceTable $Evidence
 */
class EvidenceController extends AppController
{

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->Auth->allow();
        $this->layout='portal';
    }

    /**
     * Index method
     *
     * @return void
     */
    public function index($id)
    {
        $this->layout = 'ajax';
        $this->loadModel('Schemes');
        $query = TableRegistry::get('schemes')->find();
        $result = $query
            ->select([
                'scheme_name' => 'schemes.name_en',
                'scheme_code' => 'schemes.scheme_code',
                'contract_amount' => 'schemes.contract_amount',
                'fiscal_year' => 'financial_year_estimates.name',
                'contractor_title' => 'contractors.contractor_title',
                'contractor_person_name' => 'contractors.contact_person_name',
                'contractor_address' => 'contractors.contractor_address',
                'contractor_tin_no' => 'contractors.tin_no',
                'qr_image' => 'qr_images.qr_image',
                'serve_amount' => $query->func()->sum('processed_ra_bills.bill_amount'),
            ])
            ->leftJoin('processed_ra_bills', 'processed_ra_bills.scheme_id = schemes.id')
            ->leftJoin('scheme_contractors', 'scheme_contractors.scheme_id = schemes.id')
            ->leftJoin('contractors', 'contractors.id = scheme_contractors.contractor_id')
            ->leftJoin('contractors', 'contractors.id = scheme_contractors.contractor_id')
            ->leftJoin('financial_year_estimates', 'financial_year_estimates.id = schemes.financial_year_estimate_id')
            ->leftJoin('qr_images', 'qr_images.scheme_id = schemes.id')
            ->where(['schemes.id' => $id, 'scheme_contractors.is_lead' => 1 ])
            ->first();
//        pr($result);die;
        $this->set(compact('result'));
    }

}
